# Site settings
title: Paul Yashouh - Fullstack Developer
description: My personal portfolio showcasing frontend development expertise, fullstack knowledge, and projects.
author: Paul Yashouh
email: paulyashou81@gmail.com

# GitHub Pages settings
baseurl: '' # Leave empty if deployed as payamaya.github.io
url: 'https://payamaya.github.io'

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

# Permalink style
permalink: pretty

# Header pages
header_pages:
  - index.md
  - projects.md
  - contact.md
  - contact-me.md
  - about.md
  - footer.md
