# Site settings
title: Paul Yashouh - Fullstack Developer
description: My personal portfolio showcasing frontend development expertise, fullstack knowledge, and projects.
author: Paul Yashouh
email: paulyashou81@gmail.com # Optional, but good for contact

# Base URL (for GitHub Pages)
# IMPORTANT: If your repository is `username.github.io`, leave baseurl empty.
# If your repository is `username.github.io/my-portfolio`, then set baseurl: "/my-portfolio"
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://payamaya.github.io/" # The base hostname & protocol for your site

# Theme
# This is a very common default theme that looks clean.
# You can explore others like "hyde" or search for Jekyll themes.
theme: minima

# Exclude from processing.
# The following items will not be processed, by default.
# For more information, please see:
# https://jekyllrb.com/docs/configuration/
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (if you decide to use Jekyll plugins later)
plugins:
  - jekyll-feed
  - jekyll-seo-tag # Recommended for SEO

  # Add this to your existing _config.yml
include:
  - index.css

  # Add to _config.yml
  header_pages:
  - index.md
  # Add other pages like projects.md, about.md if you have them
