name: HTMLProofer (link check)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  htmlproofer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install bundler --no-document
          bundle install --jobs 4 --retry 3

      - name: Build site
        run: bundle exec jekyll build

      - name: Install html-proofer
        run: gem install html-proofer --no-document

      - name: Run HTMLProofer
        run: |
          htmlproofer ./_site --assume-extension --check-html --allow-hash-href
